apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      name: wordpress
      release: wordpress
  template:
    metadata:
      labels:
        name: wordpress
        release: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:5.3.2-php7.2-apache
          resources:
            limits:
              memory: 200Mi
              cpu: 700m
            requests:
              memory: 256Mi
              cpu: 500m
          ports:
            - containerPort: 80
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql-service
            - name: WORDPRESS_DB_USER
              value: user
            - name: WORDPRESS_DB_PASSWORD
              value: password
            - name: WORDPRESS_DB_NAME
              value: example
          volumeMounts:
            - name: wordpress-claim
              mountPath: /var/www/html
      volumes:
        - name: wordpress-claim
          persistentVolumeClaim:
            claimName: wordpress-claim

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-claim
  labels:
    name: wordpress
    release: wordpress
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
